import { Button } from "@mantine/core";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Payment from "../src/components/payment";

export default function Home() {
  return (
    <div className="h-screen bg-[url('../public/covid.gif')] bg-no-repeat	bg-cover">
      <Head>
        <title>Code Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" align-middle items-center text-center">
        <Link href="/payment">
          <Button className=" bg-emerald-500">Donation for covid 19</Button>
        </Link>
      </main>
    </div>
  );
}
