import { Button } from "@mantine/core";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Payment from "../src/components/payment";

export default function Home() {
  return (
    <div className="h-screen ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-emerald-500">
        <Link href="/payment">
          <Button>Donation for covid 19</Button>
        </Link>
      </main>
    </div>
  );
}
